post_install() {
    sed "s/\(Categories.*$\)/\1Network;/" -i /usr/share/applications/deepin.com.qq.office.desktop
}

post_upgrade() {
    new_tim_version=$(echo $1 | sed "s/-.*//")
    echo "Updating the TIM package version..."
    find /home -maxdepth 2 -name ".deepinwine" -exec sed -i "s/.*/$new_tim_version/" \{\}/Deepin-TIM/PACKAGE_VERSION \;
}

pre_remove() {
    echo "deleting the TIM bottle..."
    find /home -maxdepth 2 -name ".deepinwine" -exec rm -rf \{\}/Deepin-TIM/ \;
}
